### ISSUE TITLE
Manually testing update.py produces error in console

### ISSUE THREAD

**Issue by johnpeele** [jordansinger/figma-slack-updates#11]
When manually testing the app via `python update.py` in the Heroku console, I receive the following error:

```
Traceback (most recent call last):
  File "/app/update.py", line 1, in <module>
    import requests
  File "/app/.heroku/python/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/app/.heroku/python/lib/python3.12/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/app/.heroku/python/lib/python3.12/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/app/.heroku/python/lib/python3.12/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

I see that very little activity has happened here in a long time, so any help I can get would be greatly appreciated!

**Comment by jenna-tart** [comment]
remove the version numbers in requirements.txt
`maya==0.6.1
requests
python-dotenv`
